"""
This type stub file was generated by pyright.
"""

from .webhook import DiscordEmbed, DiscordWebhook
from .async_webhook import AsyncDiscordWebhook

__all__ = ["DiscordWebhook", "DiscordEmbed", "AsyncDiscordWebhook"]
