"""
This type stub file was generated by pyright.
"""

import httpx
from contextlib import asynccontextmanager
from . import DiscordWebhook

logger = ...
class AsyncDiscordWebhook(DiscordWebhook):
    """
    Async version of DiscordWebhook.
    """
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    @property
    @asynccontextmanager
    async def http_client(self) -> httpx.AsyncClient:
        """
        A property that returns a httpx.AsyncClient instance that is used for a 'with' statement.
        Example:
            async with self.http_client as client:
                client.post(url, data=data)
        It will automatically close the client when the context is exited.
        :return: httpx.AsyncClient
        """
        ...
    
    async def api_post_request(self) -> httpx.Response:
        """
        Post the JSON converted webhook data to the specified url.
        :return:
        """
        ...
    
    async def handle_rate_limit(self, response, request) -> httpx.Response:
        """
        Handle the rate limit by resending the webhook until a successful response.
        :param response: Response
        :param request: request function
        :return: Response of the sent webhook
        """
        ...
    
    async def execute(self, remove_embeds=...) -> httpx.Response:
        """
        Execute the sending of the webhook with the given data.
        :param bool remove_embeds: clear the stored embeds after webhook is executed
        :return: Response of the sent webhook
        """
        ...
    
    async def edit(self) -> httpx.Response:
        """
        Edit an already sent webhook with updated data.
        :return: Response of the sent webhook
        """
        ...
    
    async def delete(self) -> httpx.Response:
        """
        Delete the already sent webhook.
        :return: webhook response
        """
        ...
    


