"""
This type stub file was generated by pyright.
"""

from typing import Union

class ColorNotInRangeException(Exception):
    """
    This Exception will be raised when a color is not in that range.

    A valid color must take an integer value between 0 and 16777216 inclusive
    """
    def __init__(self, color: Union[str, int], message=...) -> None:
        ...
    


